app/calc/forms.py
from flask_wtf import FlaskForm
from wtforms import FloatField, validators, SubmitField, StringField


class SingleEventForm(FlaskForm):
    probabilities = StringField('Probabilities separated by commas (e.g., 0.2, 0.3, 0.5)', [validators.InputRequired()])
    submit = SubmitField('Calculate')

class AddMultProbForm(FlaskForm):
    prob_a = FloatField('Enter probability A (e.g., 0.2)', [validators.InputRequired()])
    prob_b = FloatField('Enter probability B (e.g., 0.2)', [validators.InputRequired()])
    submit = SubmitField('Calculate')

class BayesForm(FlaskForm):
    prob_a = FloatField('Enter probability A (e.g., 0.2)', [validators.InputRequired()])
    prob_b = FloatField('Enter probability B (e.g., 0.2)', [validators.InputRequired()])
    prob_ba = FloatField('Enter probability B|A (e.g., 0.2)', [validators.InputRequired()])
    submit = SubmitField('Calculate')

class FullProbForm(FlaskForm):
    cond_probabilities = StringField('Probabilities separated by commas (e.g., 0.2, 0.3, 0.5)', [validators.InputRequired()])
    prior_probabilities = StringField('Probabilities separated by commas (e.g., 0.2, 0.3, 0.5)', [validators.InputRequired()])
    submit = SubmitField('Calculate')

app/__init__.py
from flask import Flask
import config

def create_app(config_name='development'):
    app = Flask(__name__)

    from config import DevelopmentConfig, ProductionConfig

    if config_name == 'production':
        app.config.from_object(ProductionConfig)
    else:
        app.config.from_object(DevelopmentConfig)

    with app.app_context():
        from .homepage.views import homepage
        from .calc.views import calc

        app.register_blueprint(homepage)
        app.register_blueprint(calc)

    return app

app/calc/__init__.py
from flask import Blueprint

calc = Blueprint('calc', __name__, template_folder='templates')

app/calc/views.py
from flask import render_template

from . import calc
from .forms import AddMultProbForm, SingleEventForm, BayesForm, FullProbForm
from .formulas import adding_formula, multiplying_formula, single_event_formula, bayes_formula, full_probability_formula


@calc.route('/adding', methods=['GET', 'POST'])
def adding():
    form = AddMultProbForm()
    result = 0

    if form.validate_on_submit():
        prob_a = form.prob_a.data
        prob_b = form.prob_b.data
        result = adding_formula(prob_a, prob_b)

    return render_template('adding.html', form=form, result=result)


@calc.route('/multiplying', methods=['GET', 'POST'])
def multiplying():
    form = AddMultProbForm()

    result = 0

    if form.validate_on_submit():
        prob_a = form.prob_a.data
        prob_b = form.prob_b.data
        result = multiplying_formula(prob_a, prob_b)

    return render_template('multiplying.html', form=form, result=result)

@calc.route('/single_event', methods=['GET', 'POST'])
def single_event():
    form = SingleEventForm()

    result = 0

    if form.validate_on_submit():
        probabilities_string = form.probabilities.data
        probabilities = [float(prob) for prob in probabilities_string.split(',')]
        result = single_event_formula(probabilities)

    return render_template('single_event.html', form=form, result=result)

@calc.route('/bayes', methods=['GET', 'POST'])
def bayes():
    result = 0
    form = BayesForm()


    if form.validate_on_submit():
        prob_a = form.prob_a.data
        prob_b = form.prob_b.data
        prob_ba = form.prob_ba.data

        result = bayes_formula(prob_a, prob_b, prob_ba)

    return render_template('bayes.html', form=form, result=result)

@calc.route('/full_prob', methods=['GET', 'POST'])
def full_prob():
    form = FullProbForm()
    result = 0
    if form.validate_on_submit():
        cond_prop_string = form.cond_probabilities.data
        cond_prop = [float(prob) for prob in cond_prop_string.split(',')]
        prior_prop_string = form.cond_probabilities.data
        prior_prop = [float(prob) for prob in prior_prop_string.split(',')]

        result = full_probability_formula(cond_prop, prior_prop)
    return render_template('full_prob.html', form=form, result=result)

app/homepage/__init__.py
from flask import Blueprint

homepage = Blueprint('homepage', __name__, template_folder='templates')

app/homepage/views.py
from flask import render_template

from . import homepage

@homepage.route('/')
@homepage.route('/home')
def home():
    return render_template('home.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Home</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
</head>
<body>
    {% include 'nav.html' %}

    <main>
        {% block content %}{% endblock %}
    </main>

    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>
</html>

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-gradient ">
  <div class="container-fluid">
    <span class="navbar-brand">Probability Calculator</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('homepage.home') }}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tools
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('calc.adding') }}">Add Calc</a></li>
            <li><a class="dropdown-item" href="{{ url_for('calc.multiplying') }}">Mult Calc</a></li>
            <li><a class="dropdown-item" href="{{ url_for('calc.single_event') }}">Single Event Calc</a></li>
            <li><a class="dropdown-item" href="{{ url_for('calc.full_prob') }}">Full Prob Calc</a></li>
            <li><a class="dropdown-item" href="{{ url_for('calc.bayes') }}">Bayes Calc</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>